apiVersion: apps/v1
kind: Deployment
metadata:
  name: didaas-docs
  labels:
    run: didaas-docs
  namespace: didaas-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: didaas-docs
  template:
    metadata:
      labels:
        app: didaas-docs
    spec:
      containers:
        - image: gcr.io/leap-0123/didaas/didaas-docs:latest
          imagePullPolicy: Always
          name: didaas-docs
          ports:
            - containerPort: 4567
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: didaas-docs
  labels:
    run: didaas-docs
  namespace: didaas-staging
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 4567
      name: didaas-docs
  selector:
    app: didaas-docs
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: didaas-docs-staging
  namespace: didaas-staging
  annotations:
    kubernetes.io/ingress.class: "nginx-internal"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - didaas-docs-staging.123leap.ca
      secretName: tls-123leap-ca-p
  rules:
    - host: didaas-docs-staging.123leap.ca
      http:
        paths:
          - path: /
            backend:
              serviceName: didaas-docs
              servicePort: 8080
